### ISSUE TITLE
Figure out how to publish components to npm

### ISSUE THREAD

**Issue by ninjha01** [nitro-bio/nitro-ui#10]
## Publishing to npm

We'd like to be able to pull these components down into a new project without having to copy and paste. This means we have to figure out how to publish these react components + typescript types to npm.

It may be a good idea to practice using Google Artifact Repository so we can have a clean public repo

## Time Estimate
10 hrs

**Comment by digithed** [comment]
Using the following code for importing the Toggle component does not result in expected behavior:

```import './App.css';
import { Card, Toggle } from "@ninjha01/nitro-ui";

function App() {
  return (
    <div>
      <Card>
      hello world
      <Toggle onClick={() => alert("hello world")}/>
      </Card>
      </div>

  );
}

export default App;

**Comment by digithed** [comment]
Screenshot of app:
<img width="1391" alt="Screen Shot 2022-11-08 at 3 08 20 PM" src="https://user-images.githubusercontent.com/31827769/200664864-300c446b-d152-4051-97e7-36232c30fd41.png">

`tailwindcss` version is `3.2.2` and `@ninjha01/nitro-ui` version is `0.0.3`

**Comment by ninjha01** [comment]
Can you try adding
`purge: ["./node_modules/@ninjha01/nitro-ui/dist/**/*.js"],` to your tailwind.config? Like
```
module.exports = {
...
purge: ["./node_modules/@ninjha01/nitro-ui/dist/**/*.js"],
...}
`

**Comment by ninjha01** [comment]
per [this comment](https://github.com/tailwindlabs/tailwindcss/discussions/6056#discussioncomment-1627523)

**Comment by ninjha01** [comment]
Check out https://github.com/ninjha01/personal-site/commit/e119f2f72ecc4bb1b2ba2b705e73058eeaa9757c and https://personal-site-git-test-nitro-ninjha01.vercel.app/

**Comment by digithed** [comment]
@ninjha01 Wow works beautifully!

**Comment by digithed** [comment]
<img width="1390" alt="Screen Shot 2022-11-08 at 5 25 45 PM" src="https://user-images.githubusercontent.com/31827769/200689333-9b0bb729-7aca-4c0d-a030-4cd4d37ef0ce.png">
