### ISSUE TITLE
Set up SeqViz styling

### ISSUE THREAD

**Issue by digithed** [nitro-bio/nitro-ui#24]
## Component Description
- Change enzyme and annotation colors
- Change color of overall circular/linear views to toggle light/dark mode and brand color

## Style Variants

- [ ] Dark Mode
- [ ] Light Mode
- [ ] Brand

## Time Estimate
5 hrs

**Comment by digithed** [comment]
@ninjha01

**Comment by ninjha01** [comment]
Closing because we're building our own sequence viewer
