### ISSUE TITLE
Fix import of the nitro stylesheet

### ISSUE THREAD

**Issue by rmcl** [nitro-bio/nitro-ui#72]
Right now to use the nitro.ui stylesheet I have to reference the node_modules folder:

```
import "../../../node_modules/@ninjha01/nitro-ui/dist/style.css";
```

but I want to be able to do something like:

```
import "@ninjha01/nitro-ui/dist/nitro.css";
```

I think this can be fixed by adding a "styles" property to package.json?

**Comment by vijib** [comment]
Any way to use this as a dark theme css instead light themed ?

**Comment by vijib** [comment]
@rmcl There is another issue labelled darkTheme wherein 1.0.7 was published but not pullable. could you help please
