### ISSUE TITLE
React Flow Component

### ISSUE THREAD

**Issue by ninjha01** [nitro-bio/nitro-ui#9]
## Component Description
Story for a architecture diagram react flow component
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/25281692/199375266-ce7d18c8-81fc-4097-b198-5a044288e09d.png">

## Style Variants
- [ ] Light Mode

## Time Estimate
4 hrs

**Comment by digithed** [comment]
@ninjha01 I can work on this while you're reviewing the current PR

**Comment by ninjha01** [comment]
Lets hold off for now
